import {
  Alignment,
  Autoformat,
  Base64UploadAdapter,
  BlockQuote,
  Bold,
  CodeBlock,
  EditorConfig,
  Essentials,
  FindAndReplace,
  Font,
  GeneralHtmlSupport,
  Heading,
  Highlight,
  HorizontalLine,
  Image,
  ImageCaption,
  ImageInsert,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  Indent,
  IndentBlock,
  Italic,
  Link,
  LinkImage,
  List,
  MediaEmbed,
  RemoveFormat,
  SourceEditing,
  Table,
  TableToolbar,
} from "ckeditor5";
import coreTranslations from "ckeditor5/translations/es.js";

export const CONFIG_EDITOR: EditorConfig = {
  plugins: [
    Essentials,
    Heading,
    Bold,
    Italic,
    Font,
    Link,
    BlockQuote,
    Autoformat,
    Indent,
    IndentBlock,
    CodeBlock,
    FindAndReplace,
    Highlight,
    HorizontalLine,
    GeneralHtmlSupport,
    SourceEditing,
    List,
    MediaEmbed,
    RemoveFormat,
    Table,
    TableToolbar,
    Alignment,
    Image,
    ImageInsert,
    ImageToolbar,
    ImageCaption,
    ImageStyle,
    ImageResize,
    LinkImage,
    Base64UploadAdapter,
  ],
  toolbar: [
    "sourceEditing",
    "findAndReplace",
    "undo",
    "redo",
    "|",
    "heading",
    "|",
    "bold",
    "italic",
    "blockQuote",
    "horizontalLine",
    "|",
    "bulletedList",
    "numberedList",
    "|",
    "fontSize",
    "fontFamily",
    "alignment",
    "fontColor",
    "fontBackgroundColor",
    "highlight",
    "|",
    "insertImage",
    "link",
    "mediaEmbed",
    "codeBlock",
    "insertTable",
    "|",
    "outdent",
    "indent",
    "|",
    "removeFormat",
  ],
  image: {
    toolbar: [
      "imageStyle:block",
      "imageStyle:side",
      "|",
      "toggleImageCaption",
      "imageTextAlternative",
      "|",
      "linkImage",
    ],
    insert: {
      integrations: ["upload", "assetManager", "url"],
    },
  },
  table: {
    contentToolbar: ["tableColumn", "tableRow", "mergeTableCells"],
  },
  heading: {
    options: [
      {
        model: "paragraph",
        title: "Paragraph",
        class: "ck-heading_paragraph",
      },
      {
        model: "heading1",
        view: {
          name: "h1",
          classes: "text-4xl",
        },
        title: "Heading 1",
        class: "ck-heading_heading1",
      },
      {
        model: "heading2",
        view: {
          name: "h2",
          classes: "text-3xl",
        },
        title: "Heading 2",
        class: "ck-heading_heading2",
      },
      {
        model: "heading3",
        view: {
          name: "h3",
          classes: "text-2xl",
        },
        title: "Heading 3",
        class: "ck-heading_heading3",
      },
    ],
  },
  menuBar: {
    isVisible: true,
  },
  language: {
    ui: "es",
    content: "es",
  },
  translations: [coreTranslations],
};
