name: Run Lint, Format, and Test

on:
  push:
    branches: ["main", "feat/**"]
  pull_request:
    branches:
      - main

jobs:
  format-lint:
    name: Format & Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies with pnpm
        run: |
          npm install -g pnpm
          pnpm install

      - name: Format
        run: pnpm format:check

      - name: Linter
        run: pnpm lint:check

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies with pnpm
        run: |
          npm install -g pnpm
          pnpm install

      - name: Run unit tests
        run: pnpm test:coverage
