name: Run Vitest Unit Tests

on:
  push:
    branches: ["main", "feat/**"]
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Linter
        run: pnpm lint:check

      - name: Format
        run: pnpm format:check

      - name: Run unit tests
        run: pnpm test:coverage
